language: java

jdk:
  - openjdk8

# Whitelist
branches:  
  only:
    - master

services:  
    # Enable docker service inside travis
    - docker

install:
    # Build the spring boot app and copy the result to the docker folder
    - mvn -U clean install && cp target/mcp-identityregistry-keycloak-spi-latest-jar-with-dependencies.jar docker/

before_script:  
    - echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin

script:
    # Build the docker image
    - docker build --no-cache -t dmadk/keycloak-mysql-mc-ha docker
    # Push the image to the repository
    - docker push dmadk/keycloak-mysql-mc-ha:latest
    # Remember to logout of docker
    - docker logout
