language: java

jdk:
  - openjdk8

# Whitelist
branches:  
  only:
    - master

services:  
    # Enable docker service inside travis
    - docker

install:
    # Build the spring boot app and copy the result to the docker folder
    - mvn -U clean install && cp target/mc-identityregistry-keycloak-spi-latest-jar-with-dependencies.jar docker/

before_script:  
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    # Build the docker image
    - docker build --no-cache -t dmadk/keycloak-mysql-mc docker
    # Push the image to the repository
    - docker push dmadk/keycloak-mysql-mc
